name: Planka
version: "25.12.11"
slug: planka
panel_icon: "mdi:view-week"
description: Kanban board open-source (Planka)
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/planka
webui: http://[HOST]:[PORT:1337]/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 1337
ports:
    1337/tcp: 1337
ports_description:
    1337/tcp: WebUI
options:
    DATABASE:
      db_host: localhost
      db_port: 5432
      db_user: planka
      db_password: homeassistant
      db_name: planka
    ADMIN:
      email: admin@example.com
      password: homeassistant
      name: Admin
schema:
    DATABASE:
      db_host: str
      db_port: int
      db_user: str
      db_password: str
      db_name: str
    ADMIN:
      email: str
      password: password
      name: str
map:
  - type: addon_config
    read_only: False
    path: /config
