name: n8n
version: "26.1.5"
slug: n8n
panel_icon: "mdi:sitemap-outline"
description: Self host your n8n instance
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/n8n
webui: http://[HOST]:[PORT:5690]/
arch:
    - armhf
    - armv7
    - aarch64
    - amd64
    - i386
startup: application
boot: auto
hassio_role: "default"
hassio_api: true
homeassistant_api: true
apparmor: true
ingress: true
ingress_port: 5690
ingress_stream: true
backup_exclude:
    - "n8n/.cache"
    - "n8n/.n8n/n8nEventLog*.log"
    - "n8n/.n8n/crash.journal"
    - "supervisord.log*"
map:
    - ssl:ro
    - backup:rw
    - share:rw
    - media:rw
    - config:rw
ports:
    5678/tcp: null
    8081/tcp: 8081
ports_description:
    5678/tcp: The port for all n8n traffic. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass the Ingress (not recommended for security reasons). See the documentation for more information.
    8081/tcp: The port for n8n webhook and API-related traffic. Use this to allow running under Home Assistant Ingress while still allowing certain public communication channels to go through and function. See the documentation for more information.
options:
    timezone: "Europe/Berlin"
    env_vars_list: []
    cmd_line_args: ""
schema:
    timezone: str
    env_vars_list: [
      "match(^[A-Z_0-9]+: .*$)"
    ]
    cmd_line_args: str?
